name: MK CHAN
favicon: null
layout_spectrum: 0.48809
typography_spectrum: 0.32691566925495863
title: MKECM IT SOLUTIONS - MK Chan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5466947907116264
  lightness: 0.7921339012682438
  saturation: 0.7350811643991619
  rhythmicContrast: 0.2811361625790596
purpose: []
