name: MK CHAN
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49276
title: MKECM IT SOLUTIONS - MK Chan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5f3b95'
    - '#faae33'
    - '#f17336'
    - '#30b45e'
    - '#ec1c23'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
